routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

Route::get('/','HomeController@index')->name('home');

Route::post('subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::get('post/{slug}', 'PostController@details')->name('post.details');

Route::get('posts', 'PostController@index')->name('post.index');

Route::get('/category/{slug}', 'PostController@postByCategory')->name('category.posts');
Route::get('/tag/{slug}', 'PostController@postByTag')->name('tag.posts');

Route::get('/search', 'SearchController@search')->name('search');

Route::get('profile/{username}', 'AuthorController@profile')->name('author.profile');

//Authentication Routes
Auth::routes();



//These are all for Admin dashboard routes and here defined file directory , prefix , namespace, middleware as default
Route::group(['as'=>'admin.','prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth', 'admin']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('tag', 'TagController');
    Route::resource('category', 'CategoryController');
    Route::resource('post', 'PostController');


    Route::get('pending/post', 'PostController@pending')->name('post.pending');
    Route::put('/post/{id}/approved', 'PostController@approval')->name('post.approved');
    Route::put('/post/{id}/approve', 'PostController@approve')->name('post.approve');


    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');

    Route::get('settings', 'SettingsController@index')->name('settings');

    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');

    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');


    Route::get('/favourite', 'FavouriteController@index')->name('favourite.index');

    Route::get('comments', 'CommentController@index')->name('comments.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');

    Route::get('authors', 'AuthorController@index')->name('author.index');
    Route::delete('authors/{id}', 'AuthorController@destroy')->name('author.destroy');

});


//These are all for Author dashboard routes and here defined file directory , prefix , namespace, middleware as default
Route::group(['as'=>'author.','prefix'=>'author', 'namespace'=>'Author', 'middleware'=>['auth', 'author']], function() {
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('post', 'PostController');

    Route::get('settings', 'SettingsController@index')->name('settings');

    Route::put('profile-update', 'SettingsController@updateProfile')->name('profile.update');

    Route::put('password-update', 'SettingsController@updatePassword')->name('password.update');

    Route::get('/favourite', 'FavouriteController@index')->name('favourite.index');

    Route::get('comments', 'CommentController@index')->name('comments.index');
    Route::delete('comments/{id}', 'CommentController@destroy')->name('comment.destroy');
});


Route::group(['middleware' => ['auth']], function() {
    Route::post('favourite/{post}/add', 'FavouriteController@addFav')->name('post.favourite');
    Route::post('comment/{post}', 'CommentController@store')->name('comment.store');
});

View::composer('layouts.frontend.partials.footer', function ($view) {
    $categories = App\Category::all();
    $view->with('categories', $categories);
});

resources/views/layouts/backend/partials/sidebar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="{{ asset('storage/profile/'.Auth::user()->image) }}" width="50" height="50" alt="User" />
        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }}</div>
            <div class="email">{{ Auth::user()->email }}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">

                    <li>
                        <a href="{{ Auth::user()->role->id == 1 ? route('admin.settings') : route('author.settings') }}">
                            <i class="material-icons">settings</i> Settings
                        </a>
                    </li>

                    <li role="separator" class="divider"></li>

                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>{{ __('Sign Out') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="p">MAIN NAVIGATION</li>

            {{--Admin Part--}}
            @if(Request::is('admin*'))
                <li class="{{ Request::is('admin/dashboard')? 'active' : '' }}">
                    <a href="{{ route('admin.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/category*')? 'active' : '' }}">
                    <a href="{{ route('admin.category.index') }}">
                        <i class="material-icons">apps</i>
                        <span>Category</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/tag*')? 'active' : '' }}">
                    <a href="{{ route('admin.tag.index') }}">
                        <i class="material-icons">label</i>
                        <span>Tag</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/post*')? 'active' : '' }}">
                    <a href="{{ route('admin.post.index') }}">
                        <i class="material-icons">library_books</i>
                        <span>Posts</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/pending/post')? 'active' : '' }}">
                    <a href="{{ route('admin.post.pending') }}">
                        <i class="material-icons">hourglass_empty</i>
                        <span>Pending Posts</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/favourite')? 'active' : '' }}">
                    <a href="{{ route('admin.favourite.index') }}">
                        <i class="material-icons">favorite</i>
                        <span>Favourite Posts</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/comments')? 'active' : '' }}">
                    <a href="{{ route('admin.comments.index') }}">
                        <i class="material-icons">comment</i>
                        <span>Comments</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/authors')? 'active' : '' }}">
                    <a href="{{ route('admin.author.index') }}">
                        <i class="material-icons">account_circle</i>
                        <span>Authors</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/subscriber')? 'active' : '' }}">
                    <a href="{{ route('admin.subscriber.index') }}">
                        <i class="material-icons">subscriptions</i>
                        <span>Subscribers</span>
                    </a>
                </li>

                <li class="header">System</li>

                <li>
                    <a target="_blank" href="{{ route('home') }}">
                        <i class="material-icons">home</i>
                        <span>View Site</span>
                    </a>
                </li>

                <li class="{{ Request::is('admin/settings')? 'active' : '' }}">
                    <a href="{{ route('admin.settings') }}">
                        <i class="material-icons">settings</i>
                        <span>Settings</span>
                    </a>
                </li>

                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="material-icons">input</i><span>{{ __('Logout') }}</span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>

            @endif
            {{--Admin Part End--}}


            {{--Author Part--}}
            @if(Request::is('author*'))
                <li class="{{ Request::is('author/dashboard')? 'active' : '' }}">
                    <a href="{{ route('author.dashboard') }}">
                        <i class="material-icons">dashboard</i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="{{ Request::is('author/post*')? 'active' : '' }}">
                    <a href="{{ route('author.post.index') }}">
                        <i class="material-icons">library_books</i>
                        <span>Posts</span>
                    </a>
                </li>

                <li class="{{ Request::is('author/favourite')? 'active' : '' }}">
                    <a href="{{ route('author.favourite.index') }}">
                        <i class="material-icons">favorite</i>
                        <span>Favourite Posts</span>
                    </a>
                </li>

                <li class="{{ Request::is('author/comments')? 'active' : '' }}">
                    <a href="{{ route('author.comments.index') }}">
                        <i class="material-icons">comment</i>
                        <span>Comments</span>
                    </a>
                </li>

                <li class="header">System</li>

                <li>
                    <a target="_blank" href="{{ route('home') }}">
                        <i class="material-icons">home</i>
                        <span>View Site</span>
                    </a>
                </li>

                <li class="{{ Request::is('author/settings')? 'active' : '' }}">
                    <a href="{{ route('author.settings') }}">
                        <i class="material-icons">settings</i>
                        <span>Settings</span>
                    </a>
                </li>

                <li>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        <i class="material-icons">input</i><span>{{ __('Logout') }}</span>
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>

            @endif
            {{--Author Part End--}}


        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; 2016 - 2017 <a href="javascript:void(0);">MI SHAJIB</a>.
        </div>
        <div class="version">
            <b>Version: </b> 1.0.5
        </div>
    </div>
    <!-- #Footer -->
</aside>

resources/views/layouts/backend/partials/topbar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ route('admin.dashboard') }}">{{ __('Laravel Blog System') }}</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
                <!-- #END# Call Search -->

            </ul>
        </div>
    </div>
</nav>